#!/usr/bin/env python3
"""Generate analytically known synthetic channels for golden testing.

Produces Touchstone fixtures whose correct simulation results are known in
closed form, so integration tests can assert exact numbers:

  golden/ideal_delay.s2p   Lossless matched delay line, tau = 1.0 ns.
                           Known: impulse peak at exactly tau, pulse peak
                           1.0 V, statistical eye height 2.0 V, zero ISI.

  golden/rc_pole.s2p       Matched single-pole low-pass, fc = 8 GHz.
                           Known: worst-case NRZ eye opening at phase phi is
                           2*(1 - 2*exp(-phi/tau_c)), tau_c = 1/(2*pi*fc).

  test_channel.s2p         Causal lossy line (skin + dielectric loss),
                           tau = 2.0 ns, |S21| = 1 at DC, strictly passive.
                           Replaces the previous hand-rolled fixture whose
                           coarse data was non-passive (max singular value
                           1.0547, triggering enforcement on every run).

  test_channel_4port.s4p   Two uncoupled copies of the lossy line wired as
                           a differential pair (1->2, 3->4). Known: SDD21
                           equals the line response exactly and SDC21 =
                           SCD21 = 0 (no mode conversion).

All files are RI format, 50 ohm reference. Pure numpy; no other deps.
"""

import os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))

C_DB_TO_NEPER = np.log(10) / 20.0  # 1 dB = 0.1151 neper


def write_touchstone_2port(path, f_hz, s11, s21, s12, s22, header):
    """Touchstone 1.0 2-port, spec column order: S11 S21 S12 S22 (RI)."""
    with open(path, "w") as f:
        for line in header:
            f.write(f"! {line}\n")
        f.write("# HZ S RI R 50\n")
        for i, freq in enumerate(f_hz):
            vals = []
            for s in (s11[i], s21[i], s12[i], s22[i]):
                vals.append(f"{s.real:.9e} {s.imag:.9e}")
            f.write(f"{freq:.6e} " + " ".join(vals) + "\n")


def write_touchstone_4port(path, f_hz, smatrix, header):
    """Touchstone 1.0 4-port, row-major S11 S12 ... S44, one line per freq."""
    with open(path, "w") as f:
        for line in header:
            f.write(f"! {line}\n")
        f.write("# HZ S RI R 50\n")
        for i, freq in enumerate(f_hz):
            vals = []
            for r in range(4):
                for c in range(4):
                    s = smatrix[i, r, c]
                    vals.append(f"{s.real:.9e} {s.imag:.9e}")
            f.write(f"{freq:.6e} " + " ".join(vals) + "\n")


def ideal_delay(f_hz, tau_s):
    """Lossless matched line: S21 = exp(-j*2*pi*f*tau), S11 = 0."""
    s21 = np.exp(-1j * 2 * np.pi * f_hz * tau_s)
    zero = np.zeros_like(s21)
    return zero, s21, s21.copy(), zero.copy()


def rc_pole(f_hz, fc_hz):
    """Matched single-pole low-pass: S21 = 1 / (1 + j*f/fc), S11 = 0.

    Minimum-phase and strictly passive (|S21| <= 1).
    """
    s21 = 1.0 / (1.0 + 1j * f_hz / fc_hz)
    zero = np.zeros_like(s21)
    return zero, s21, s21.copy(), zero.copy()


def lossy_line(f_hz, tau_s, k_skin_db_per_sqrt_ghz, k_diel_db_per_ghz):
    """Causal lossy transmission line, matched (S11 = 0).

    Skin-effect loss scales with sqrt(f) and carries an equal imaginary
    part (the (1+j)*sqrt(f) form is the Hilbert-consistent pair), and
    dielectric loss scales linearly with f. |S21(0)| = 1 exactly.
    """
    f_ghz = f_hz / 1e9
    alpha_skin = k_skin_db_per_sqrt_ghz * C_DB_TO_NEPER * np.sqrt(f_ghz)
    alpha_diel = k_diel_db_per_ghz * C_DB_TO_NEPER * f_ghz
    s21 = np.exp(
        -(1 + 1j) * alpha_skin - alpha_diel - 1j * 2 * np.pi * f_hz * tau_s
    )
    zero = np.zeros_like(s21)
    return zero, s21, s21.copy(), zero.copy()


def main():
    golden_dir = os.path.join(HERE, "golden")
    os.makedirs(golden_dir, exist_ok=True)

    # --- golden/ideal_delay.s2p ------------------------------------------
    # Band edge Nyquist-aligned with the PCIe Gen 5 UI: 32 GHz = 2/UI, so a
    # band-limited 1 UI rectangle has nulls exactly at UI offsets and the
    # zero-ISI expectation survives the band limit (arbitrary band edges
    # fold sinc ringing into apparent ISI in the worst-case analyzer).
    tau = 1.0e-9
    f = np.linspace(10e6, 32e9, 1000)
    s = ideal_delay(f, tau)
    write_touchstone_2port(
        os.path.join(golden_dir, "ideal_delay.s2p"), f, *s,
        header=[
            "GOLDEN FIXTURE - generated by generate_golden_channels.py",
            "Ideal lossless matched delay line, tau = 1.0 ns",
            "Known results: impulse peak at 1.0 ns, pulse peak 1.0,",
            "statistical eye height 2.0 (zero ISI), IL = 0 dB",
        ],
    )

    # --- golden/rc_pole.s2p ----------------------------------------------
    # Wide grid (100 GHz): the pole still has |H| = 0.08 at band edge, and
    # truncating earlier smooths the exponential corner that sets the
    # worst-case eye, pulling the measured opening below the closed form.
    fc = 8e9
    f_rc = np.linspace(10e6, 100e9, 1500)
    s = rc_pole(f_rc, fc)
    write_touchstone_2port(
        os.path.join(golden_dir, "rc_pole.s2p"), f_rc, *s,
        header=[
            "GOLDEN FIXTURE - generated by generate_golden_channels.py",
            "Matched single-pole low-pass, fc = 8 GHz (tau_c = 19.894 ps)",
            "Known result: worst-case NRZ eye opening at phase phi is",
            "2*(1 - 2*exp(-phi/tau_c)) for UI-aligned sampling",
        ],
    )

    # --- test_channel.s2p (replaces non-passive hand-rolled file) --------
    f_tc = np.linspace(100e6, 20e9, 500)
    tau_tc = 2.0e-9
    k_skin, k_diel = 0.3, 0.08  # dB/sqrt(GHz), dB/GHz -> ~2.5 dB at 16 GHz
    s = lossy_line(f_tc, tau_tc, k_skin, k_diel)
    write_touchstone_2port(
        os.path.join(HERE, "test_channel.s2p"), f_tc, *s,
        header=[
            "Synthetic PCIe Gen 5 test channel - generate_golden_channels.py",
            "Causal lossy line: skin 0.3 dB/sqrt(GHz), dielectric 0.08 dB/GHz,",
            "delay 2.0 ns, matched (S11 = 0), strictly passive, S21(DC) = 1",
            f"IL at 16 GHz (Gen5 Nyquist): "
            f"{k_skin * 4 + k_diel * 16:.2f} dB",
        ],
    )

    # --- test_channel_4port.s4p (uncoupled differential pair) ------------
    _, s21_tc, _, _ = s
    n = len(f_tc)
    m = np.zeros((n, 4, 4), dtype=complex)
    # Pair P: ports 1 -> 2; pair N: ports 3 -> 4; no coupling.
    m[:, 0, 1] = s21_tc
    m[:, 1, 0] = s21_tc
    m[:, 2, 3] = s21_tc
    m[:, 3, 2] = s21_tc
    write_touchstone_4port(
        os.path.join(HERE, "test_channel_4port.s4p"), f_tc, m,
        header=[
            "Synthetic 4-port differential channel - generate_golden_channels.py",
            "Two uncoupled copies of test_channel.s2p: (1->2) and (3->4)",
            "Known results: SDD21 = single-ended S21 exactly,",
            "SDC21 = SCD21 = 0 (no mode conversion)",
        ],
    )

    for name in (
        "golden/ideal_delay.s2p",
        "golden/rc_pole.s2p",
        "test_channel.s2p",
        "test_channel_4port.s4p",
    ):
        print(f"wrote {os.path.join(HERE, name)}")


if __name__ == "__main__":
    main()
