//! Golden-channel integration tests.
//!
//! These parse synthetic Touchstone fixtures whose correct results are known
//! in closed form (generated by `examples/generate_golden_channels.py`) and
//! assert the full parse → condition → convert → eye pipeline against the
//! analytic answers. Unlike unit tests, a physics regression anywhere in the
//! chain (units, delay handling, windowing, folding) shows up here as a
//! numeric mismatch against a formula, not against a previously recorded
//! output.

use lib_dsp::eye::StatisticalEyeAnalyzer;
use lib_dsp::passivity::check_passivity;
use lib_dsp::resample_waveform;
use lib_dsp::sparam_convert::{sparam_to_impulse, sparam_to_pulse, ConversionConfig};
use lib_ibis::parse_touchstone;
use lib_types::sparams::{MixedModeSParameters, SParameters};
use lib_types::units::Seconds;
use lib_types::waveform::Waveform;

/// PCIe Gen 5 unit interval (32 GT/s NRZ).
const UI: f64 = 31.25e-12;
const SAMPLES_PER_UI: usize = 64;

fn load_fixture(rel: &str) -> SParameters {
    let path = format!("{}/../../examples/{}", env!("CARGO_MANIFEST_DIR"), rel);
    let content = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("missing fixture {path}: {e} — run examples/generate_golden_channels.py"));
    parse_touchstone(&content).expect("fixture must parse").sparams
}

fn impulse_integral(impulse: &Waveform) -> f64 {
    impulse.samples.iter().sum::<f64>() * impulse.dt.0
}

/// Time of the impulse peak on the absolute time axis.
fn impulse_peak_time(impulse: &Waveform) -> f64 {
    let argmax = impulse
        .samples
        .iter()
        .enumerate()
        .max_by(|a, b| a.1.abs().partial_cmp(&b.1.abs()).unwrap())
        .map(|(i, _)| i)
        .unwrap();
    impulse.t_start.0 + argmax as f64 * impulse.dt.0
}

/// Full statistical-eye path: pulse response resampled onto the UI grid.
fn statistical_eye_height(sp: &SParameters) -> f64 {
    let config = ConversionConfig {
        bit_time: Seconds(UI),
        ..Default::default()
    };
    let pulse = sparam_to_pulse(sp, &config).unwrap();
    let target_dt = Seconds(UI / SAMPLES_PER_UI as f64);
    let aligned = resample_waveform(&pulse, target_dt).unwrap();
    let analyzer = StatisticalEyeAnalyzer::new(SAMPLES_PER_UI);
    analyzer.analyze(&aligned).eye_height()
}

#[test]
fn golden_ideal_delay_line() {
    // S21 = exp(-j*2*pi*f*tau), tau = 1.0 ns: a perfect wire with delay.
    let sp = load_fixture("golden/ideal_delay.s2p");
    let config = ConversionConfig {
        bit_time: Seconds(UI),
        ..Default::default()
    };

    let impulse = sparam_to_impulse(&sp, &config).unwrap();

    // Energy normalization: integral of h(t) dt = S21(0) = 1 exactly.
    let integral = impulse_integral(&impulse);
    assert!(
        (integral - 1.0).abs() < 0.03,
        "ideal delay: ∫h dt = {integral}, expected 1.0"
    );

    // Group-delay preservation: the impulse must peak at tau = 1.0 ns.
    let t_peak = impulse_peak_time(&impulse);
    assert!(
        (t_peak - 1.0e-9).abs() < 0.1e-9,
        "ideal delay: impulse peak at {:.3} ns, expected 1.0 ns",
        t_peak * 1e9
    );

    // Pulse amplitude: a 1 UI rectangle of height 1.0 V. The peak rides
    // ~9% above the flat top: a brick-wall band limit (40 GHz fixture) on an
    // ideal rectangle necessarily produces Gibbs overshoot (theoretical
    // ≈ 8.95%). The settled amplitude is covered by the eye assertion below.
    let pulse = sparam_to_pulse(&sp, &config).unwrap();
    let peak = pulse.max_abs();
    assert!(
        peak > 0.95 && peak < 1.13,
        "ideal delay: pulse peak {peak}, expected 1.0 + Gibbs overshoot (≤ ~9%)"
    );

    // Zero ISI: statistical eye opens to (nearly) the full 2.0 V.
    let eye = statistical_eye_height(&sp);
    assert!(
        eye > 1.85 && eye <= 2.02,
        "ideal delay: eye height {eye}, expected ≈ 2.0 (zero ISI)"
    );
}

#[test]
fn golden_rc_pole_eye_matches_closed_form() {
    // S21 = 1/(1 + j f/fc), fc = 8 GHz. For NRZ through a single pole the
    // worst-case folded cursors are geometric, and the eye opening at
    // sampling phase phi has the closed form 2*(1 - 2*exp(-phi/tau_c)).
    // The opening is monotonic in phi, so the analyzer's max-over-phases
    // equals the expression near phi = UI.
    let fc = 8.0e9;
    let tau_c = 1.0 / (2.0 * std::f64::consts::PI * fc);

    let expected_hi = 2.0 * (1.0 - 2.0 * (-UI / tau_c).exp());
    let phi_lo = UI * (SAMPLES_PER_UI as f64 - 1.0) / SAMPLES_PER_UI as f64;
    let expected_lo = 2.0 * (1.0 - 2.0 * (-phi_lo / tau_c).exp());

    let sp = load_fixture("golden/rc_pole.s2p");
    let eye = statistical_eye_height(&sp);

    // Pipeline effects (40 GHz truncation + Kaiser taper) smooth the
    // exponential edge slightly; allow ±0.08 V around the analytic band.
    assert!(
        eye > expected_lo - 0.08 && eye < expected_hi + 0.08,
        "rc pole: eye height {eye:.4}, closed form predicts {expected_lo:.4}..{expected_hi:.4}"
    );

    // DC normalization holds for the pole too: H(0) = 1.
    let config = ConversionConfig {
        bit_time: Seconds(UI),
        ..Default::default()
    };
    let impulse = sparam_to_impulse(&sp, &config).unwrap();
    let integral = impulse_integral(&impulse);
    assert!(
        (integral - 1.0).abs() < 0.03,
        "rc pole: ∫h dt = {integral}, expected 1.0"
    );
}

#[test]
fn golden_lossy_line_passive_and_normalized() {
    // Causal skin+dielectric loss line: strictly passive by construction,
    // S21(DC) = 1, delay 2.0 ns, IL(16 GHz) = 0.3*sqrt(16) + 0.08*16 dB.
    let sp = load_fixture("test_channel.s2p");

    // Must be passive as parsed at every frequency — no enforcement (and
    // no warning) needed.
    assert!(
        check_passivity(&sp).iter().all(|&p| p),
        "lossy line fixture must be strictly passive as generated"
    );

    // Parsed IL at 16 GHz (Gen 5 Nyquist) matches the generator formula.
    let f_target = 16.0e9;
    let idx = sp
        .frequencies
        .iter()
        .enumerate()
        .min_by(|a, b| {
            (a.1 .0 - f_target)
                .abs()
                .partial_cmp(&(b.1 .0 - f_target).abs())
                .unwrap()
        })
        .map(|(i, _)| i)
        .unwrap();
    let s21 = sp.get_parameter(1, 0)[idx];
    let il_db = -20.0 * s21.norm().log10();
    let expected_il = 0.3 * (16.0f64).sqrt() + 0.08 * 16.0;
    assert!(
        (il_db - expected_il).abs() < 0.05,
        "lossy line: IL(16 GHz) = {il_db:.3} dB, generator formula gives {expected_il:.3} dB"
    );

    let config = ConversionConfig {
        bit_time: Seconds(UI),
        ..Default::default()
    };
    let impulse = sparam_to_impulse(&sp, &config).unwrap();

    let integral = impulse_integral(&impulse);
    assert!(
        (integral - 1.0).abs() < 0.03,
        "lossy line: ∫h dt = {integral}, expected S21(0) = 1.0"
    );

    let t_peak = impulse_peak_time(&impulse);
    assert!(
        (t_peak - 2.0e-9).abs() < 0.2e-9,
        "lossy line: impulse peak at {:.3} ns, expected 2.0 ns",
        t_peak * 1e9
    );
}

#[test]
fn golden_uncoupled_s4p_has_zero_mode_conversion() {
    // The 4-port fixture is two uncoupled copies of the 2-port line wired
    // as (1->2) and (3->4): SDD21 must equal the single-ended S21 exactly
    // and the cross-mode terms must vanish.
    let path = format!(
        "{}/../../examples/test_channel_4port.s4p",
        env!("CARGO_MANIFEST_DIR")
    );
    let content = std::fs::read_to_string(&path).expect("4-port fixture");
    let ts = parse_touchstone(&content).expect("must parse");
    assert_eq!(ts.sparams.num_ports, 4);

    let se = load_fixture("test_channel.s2p");
    let mm = MixedModeSParameters::from_single_ended(&ts.sparams);

    let sdd21 = mm.sdd21();
    let s21 = se.get_parameter(1, 0);
    for (i, (dd, single)) in sdd21.iter().zip(s21.iter()).enumerate() {
        assert!(
            (dd.norm() - single.norm()).abs() < 1e-9,
            "SDD21 must equal single-ended S21 for uncoupled pair (point {i}): {} vs {}",
            dd.norm(),
            single.norm()
        );
    }

    for (i, dc) in mm.sdc21().iter().enumerate() {
        assert!(
            dc.norm() < 1e-9,
            "SDC21 must be 0 for uncoupled pair, got {} at point {i}",
            dc.norm()
        );
    }

    // mode_conversion_ratio returns LINEAR ratios; for zero coupling both
    // must be exactly 0.0 (the orchestrator converts to dB for display —
    // treating these as dB was the source of a spurious warning on every
    // differential run).
    for (i, (sdc, scd)) in mm.mode_conversion_ratio().iter().enumerate() {
        assert!(
            *sdc < 1e-9 && *scd < 1e-9,
            "mode conversion ratios must be 0 for uncoupled pair, got ({sdc}, {scd}) at {i}"
        );
    }
}
